route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'admin'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: admin
    slack_configs:
    - channel: "#prometheus"
      api_url: "https://hooks.slack.com/services/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"

 
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
  



