---
- name: Deploy and configure PostgreSQL
  hosts: database
  become: yes
  vars:
    postgres_db_name: mydatabase
    postgres_db_user: myuser
    postgres_db_password: mypassword
    backup_dir: /var/backups/postgresql
    backup_script_path: /usr/local/bin/backup.sh

  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Configure PostgreSQL pg_hba.conf
      template:
        src: templates/pg_hba.conf.j2
        dest: /etc/postgresql/12/main/pg_hba.conf
      notify: Reload PostgreSQL

    - name: Create PostgreSQL database
      postgresql_db:
        name: "{{ postgres_db_name }}"
        state: present

    - name: Create PostgreSQL user
      postgresql_user:
        name: "{{ postgres_db_user }}"
        password: "{{ postgres_db_password }}"
        priv: "ALL"
        db: "{{ postgres_db_name }}"
        state: present

    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Copy backup script to server
      copy:
        src: scripts/backup.sh
        dest: "{{ backup_script_path }}"
        mode: '0755'

    - name: Setup cron job for database backup
      cron:
        name: "PostgreSQL Backup"
        minute: "0"
        hour: "3"
        job: "{{ backup_script_path }} {{ postgres_db_name }} {{ postgres_db_user }} {{ postgres_db_password }} {{ backup_dir }}"

  handlers:
    - name: Reload PostgreSQL
      service:
        name: postgresql
        state: reloaded
