---
- name: Configure Kubernetes Nodes
  hosts: kubernetes_nodes
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Download Kubernetes GPG key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /tmp/kubernetes-apt-key.gpg

    - name: Add Kubernetes GPG key
      command: apt-key add /tmp/kubernetes-apt-key.gpg
      args:
        removes: /tmp/kubernetes-apt-key.gpg

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
        filename: kubernetes
        state: present
        update_cache: yes

    - name: Install Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Hold Kubernetes packages at current version
      apt:
        name: "{{ item }}"
        state: held
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Enable and start kubelet service
      service:
        name: kubelet
        state: started
        enabled: yes
