---
- name: Install Docker and Run an image
  hosts: all
  tasks: 
    - name: install python and Docker
      apt:
        name:
          - python3
          - python3-pip
          - docker.io
        state: present

    - name: Enable docker servcie
      systemd:
        name: docker
        enabled: yes

    - name: Start the docker servcie
      systemd:
        name: docker
        state: started

    - name: Pulling docker image
      docker_image:
        name: eklavya163940/jenkins-docker
        tag: latest
        source: pull

    - name: Running docker container
      docker_container:
        name: my_test_container
        image: eklavya163940/jenkins-docker
        state: started
        restart_policy: always
        ports:
          - "80:80"