pipeline{
    agent any

    tools {
        maven 'Maven-3.9.8'
    }

    stages{
        stage('Build'){
            steps{
                sh 'mvn clean install'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }
        stage('Archive Artifacts'){
            steps{
                archiveArtifacts artifacts: '**/target/*.tar', allowEmptyArchive: true
            }
        }
    }

    post{
        always{
            echo "Pipeline Finished"
        }

        success{
            echo "Pipeline is compiled Successfully"
        }

        failure{
            echo "Pipeline failed"
        }
    }
}